package com.paosntech.common;

import lombok.Getter;

@Getter
public enum ResultEnum {

    ERROR(-1, "ERROR"),

    SUCCESS(200, "SUCCESS"),

    PARAM_ERROR(1, "PARAM_ERROR"),

    USERNAME_EXIST(2, "USERNAME_EXIST"),

    USERNAME_OR_PASSWORD_ERROR(3, "USERNAME_OR_PASSWORD_ERROR"),

    PRODUCT_NOT_EXIST(10, "PRODUCT_NOT_EXIST"),

    PRODUCT_STOCK_ERROR(11, "PRODUCT_STOCK_ERROR"),

    ORDER_NOT_EXIST(12, "ORDER_NOT_EXIST"),

    ORDERDETAIL_NOT_EXIST(13, "ORDERDETAIL_NOT_EXIST"),

    ORDER_STATUS_ERROR(14, "ORDER_STATUS_ERROR"),

    ORDER_UPDATE_FAIL(15, "ORDER_UPDATE_FAIL"),

    ORDER_DETAIL_EMPTY(16, "ORDER_DETAIL_EMPTY"),

    ORDER_PAY_STATUS_ERROR(17, "ORDER_PAY_STATUS_ERROR"),

    CART_EMPTY(18, "CART_EMPTY"),

    ORDER_OWNER_ERROR(19, "ORDER_OWNER_ERROR"),

    WECHAT_MP_ERROR(20, "WECHAT_MP_ERROR"),

    WXPAY_NOTIFY_MONEY_VERIFY_ERROR(21, "WXPAY_NOTIFY_MONEY_VERIFY_ERROR"),

    ORDER_CANCEL_SUCCESS(22, "ORDER_CANCEL_SUCCESS"),

    ORDER_FINISH_SUCCESS(23, "ORDER_FINISH_SUCCESS"),

    PRODUCT_STATUS_ERROR(24, "PRODUCT_STATUS_ERROR"),

    LOGIN_FAIL(25, "LOGIN_FAIL"),

    NEED_LOGIN(27, "NEED_LOGIN"),

    LOGOUT_SUCCESS(26, "LOGOUT_SUCCESS"),
    ;


    private Integer code;

    private String desc;

    ResultEnum(Integer code, String desc) {
        this.code = code;
        this.desc = desc;
    }
}